### ISSUE TITLE
 What is the difference? 

### ISSUE THREAD

**Issue by noob2020** [dcoinfo/WhatsApp-Api-Xtreme#1]
with Chat-Api (mgp25)??

**Comment by dcoinfo** [comment]
New updates, functions and Version.

**Comment by eaba** [comment]
Hello @dcoinfo thanks for this!
Is it possible for you to highlight what the updates, functions are!
What about WA 2.0? Is it implemented with this release? Do you plan of doing so, if this api does not support wa 2.0?
