### ISSUE TITLE
Check if number exists

### ISSUE THREAD

**Issue by TobiasZimmermannn** [dcoinfo/WhatsApp-Api-Xtreme#2]
Hi,
first of all thanks on continuing this project.
Is it possible to check if a number exists in whatsapp/ is connected to whatsapp?

Regards

**Comment by prajeshmadhavi** [comment]
Yes it is possible using contactsync.php

**Comment by dcoinfo** [comment]
GOD Bless. For Your Help **prajeshmadhavi**. And **TobiasZimmermannn** for your question.
